const API_BASE=(window.FINCELYA_ADMIN_API||'').replace(/\/$/,'');
let token=null,self=null,pending=null,rows=[];
const el=id=>document.getElementById(id),show=text=>el('message').textContent=text;
async function api(path,body){const r=await fetch(API_BASE+path,{method:body?'POST':'GET',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error?.message||'İşlem başarısız.');return data;}
function renderUsers(query=''){const q=query.toLocaleLowerCase('tr');el('users').replaceChildren();for(const row of rows.filter(x=>(x.user_id+' '+(x.display_name||'')).toLocaleLowerCase('tr').includes(q))){const tr=document.createElement('tr');for(const value of [row.user_id,row.display_name||'—',row.balance.toLocaleString('tr-TR')]){const td=document.createElement('td');td.textContent=value;tr.append(td)}const td=document.createElement('td'),button=document.createElement('button');button.className='select-user';button.textContent='Seç';button.onclick=()=>{el('target').value=row.user_id;location.hash='wallet'};td.append(button);tr.append(td);el('users').append(tr)}}
async function health(){try{const r=await fetch(API_BASE+'/live');if(!r.ok)throw Error();el('apiState').textContent='Çevrimiçi';el('serviceState').textContent='Aktif'}catch{el('apiState').textContent='Erişilemiyor';el('serviceState').textContent='Hata'}}
async function refresh(){const data=await api('/v1/admin/accounts');self=data.administratorID;rows=data.users;renderUsers(el('search').value);const audits=(await api('/v1/admin/audit')).entries;el('auditList').replaceChildren();for(const entry of audits){const item=document.createElement('div');item.className='audit-item';const date=document.createElement('span'),action=document.createElement('b'),target=document.createElement('span');date.textContent=new Date(entry.created_at).toLocaleString('tr-TR');action.textContent=entry.action;target.textContent=entry.target_user_id||'—';item.append(date,action,target);el('auditList').append(item)}el('accountCount').textContent=rows.length.toLocaleString('tr-TR');el('diamondTotal').textContent=rows.reduce((a,b)=>a+b.balance,0).toLocaleString('tr-TR');el('auditCount').textContent=audits.length.toLocaleString('tr-TR');el('panel').hidden=false;el('login').hidden=true;el('logout').hidden=false;return data}
el('loginForm').onsubmit=async e=>{e.preventDefault();try{show('Giriş yapılıyor…');const config=await(await fetch(API_BASE+'/admin/config')).json();const r=await fetch(config.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.publishableKey,'content-type':'application/json'},body:JSON.stringify({email:el('email').value,password:el('password').value})});el('password').value='';const data=await r.json();if(!r.ok)throw Error('E-posta veya şifre hatalı.');token=data.access_token;await refresh();show('')}catch(e){token=null;show(e.message)}};
el('logout').onclick=()=>{token=null;self=null;rows=[];el('panel').hidden=true;el('login').hidden=false;el('logout').hidden=true;show('Oturum kapatıldı.')};el('refresh').onclick=()=>refresh().catch(e=>show(e.message));el('search').oninput=e=>renderUsers(e.target.value);
async function adjust(targetID,amount,reason){const signature=JSON.stringify({targetID,amount,reason});if(pending?.signature!==signature)pending={signature,requestID:crypto.randomUUID()};await api('/v1/admin/wallet',{targetID,amount,reason,requestID:pending.requestID});pending=null;await refresh();show('Bakiye güncellendi.')}
el('adjustForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await adjust(el('target').value.trim(),Number(el('amount').value),el('reason').value.trim())}catch(e){show(e.message)}finally{button.disabled=false}};
el('testCredit').onclick=async()=>{el('testCredit').disabled=true;try{const data=await refresh(),own=data.users.find(u=>u.user_id===self);if(!own)throw Error('Kendi hesabınız listede bulunamadı.');const amount=1000000-own.balance;if(amount<=0)return show('Test bakiyeniz zaten yeterli.');await adjust(self,amount,'Yönetici test bakiyesi')}catch(e){show(e.message)}finally{el('testCredit').disabled=false}};
el('appleProducts').onclick=async()=>{el('appleProducts').disabled=true;try{el('appleResult').textContent=JSON.stringify(await api('/v1/admin/appstore/products'),null,2)}catch(e){el('appleResult').textContent=e.message}finally{el('appleProducts').disabled=false}};
async function completeRecovery(){
  const hash=new URLSearchParams(location.hash.slice(1));
  if(hash.get('error')){show(hash.get('error_code')==='otp_expired'?'Bu şifre bağlantısının süresi dolmuş. Yeni bağlantı isteyin.':hash.get('error_description')||'Bağlantı geçersiz.');return;}
  const access=hash.get('access_token');if(!access||hash.get('type')!=='recovery')return;
  const password=prompt('Fincelya yönetici hesabı için yeni şifrenizi girin (en az 12 karakter):');
  if(!password)return show('Şifre belirleme iptal edildi.');
  if(password.length<12)return show('Şifre en az 12 karakter olmalıdır.');
  try{const config=await(await fetch(API_BASE+'/admin/config')).json();const r=await fetch(config.url+'/auth/v1/user',{method:'PUT',headers:{apikey:config.publishableKey,authorization:`Bearer ${access}`,'content-type':'application/json'},body:JSON.stringify({password})});const data=await r.json();if(!r.ok)throw Error(data.msg||data.message||'Şifre güncellenemedi.');history.replaceState(null,'',location.pathname);token=access;await refresh();show('Şifreniz oluşturuldu ve yönetici oturumu açıldı.');}catch(e){show(e.message)}
}
completeRecovery();health();

